GENRE_DISCOVER_CHOICES = {
    ("Pop", "POP"),
    ("Rap", "RAP"),
    ("Hip Hop", "HIP HOP"),
    ("R&B", "R&B"),
    ("Edm", "EDM"),
    ("Rock", "ROCK"),
    ("Metalcore", "METALCORE"),
    ("Trap", "TRAP"),
    ("Jazz", "JAZZ"),
    ("Latin", "LATIN"),
    ("Grunge", "GRUNGE"),
    ("Classical", "CLASSICAL"),
    ("Disco", "DISCO"),
    ("Reggae", "REGGAE"),
    ("Funk", "FUNK"),
    ("Soul", "SOUL"),
    ("Folk", "FOLK"),
    ("Heavy Metal", "HEAVY METAL"),
    ("Country", "COUNTRY"),
    ("Ambient", "AMBIENT"),
    ("Dance", "DANCE"),
    ("Alternative", "ALTERNATIVE"),
    ("Sleep", "SLEEP"),
    ("Punk", "PUNK"),
    ("Emo", "EMO")
}